#!/bin/zsh

if [[ -e /etc/pam.d/sudo_local ]]; then
    echo "TouchID unlock already in place"
else
    sudo cp /etc/pam.d/sudo_local.template /etc/pam.d/sudo_local
    sudo sed -i '' 's/#auth/auth/' /etc/pam.d/sudo_local
    echo "TouchID unlock enabled"
fi
