#!/bin/sh

bail() {
    echo fail: $*
    exit 1
}

[[ "$PUBLISH_HOST" != "" ]] && [[ "$publish_host" = "" ]] && publish_host="$PUBLISH_HOST"
[[ "$PUBLISH_DIR" != "" ]] && [[ "$publish_dir" = "" ]] && publish_dir="$PUBLISH_DIR"

orig_pwd="$PWD"
while ! [[ -f .publish ]]; do
  [[ "$PWD" = "/" ]] && bail "no .publish file found"
  cd ..
done
subdir="${PWD#$orig_pwd}"

source .publish
cd "$orig_pwd"

if [[ $# -eq 0 ]]; then
    scp -r * "$publish_host":"${publish_dir}${subdir}"
else
    scp "$@" "$publish_host":"${publish_dir}${subdir}"
fi
