#!/bin/sh

function usage() {
  NAME=$(basename "$0")
  echo "Usage: ${NAME} <source-icon> <output-directory>"
}

IN_FILE="$1"
OUT_DIR="$2"

if [[ ! -r "$IN_FILE" ]]; then
  echo "Missing source icon, or file not found: $IN_FILE"
  usage
  exit 1
fi
if [[ ! -d "$OUT_DIR" ]]; then
  echo "Missing output directory, or directory not found: $OUT_DIR"
  usage
  exit 2
fi

echo "* Generating App Store icon at 1024x1024 px"
retina-scale "$IN_FILE" "$OUT_DIR" "$PREFIX" $SIZE $SIZE
APPSTORE_FILE="${OUT_DIR}/${PREFIX}_1024.png"
echo "> convert '${IN_FILE}' -scale 1024x1024 '${APPSTORE_FILE}'"
gm convert "$IN_FILE" -scale 1024x1024 "$APPSTORE_FILE"

for SIZE in 20 29 40 60 76 83.5; do
  FILENAME=$(basename "$IN_FILE")
  PREFIX="${FILENAME%.png}_$SIZE"
  echo "* Generating app icons at $SIZE points with filename prefix $PREFIX"
  retina-scale "$IN_FILE" "$OUT_DIR" "$PREFIX" $SIZE $SIZE
done
