#!/bin/sh

for svc in $HOME/Library/LaunchAgents/*; do
  echo "* Unloading $svc"
  launchctl unload "$svc"
done

for svc in /Library/LaunchAgents/* /Library/LaunchDaemons/*; do
  echo "* Unloading $svc"
  sudo launchctl unload "$svc"
done
