#!/bin/sh

for svc in $HOME/Library/LaunchAgents/*; do
  echo "* Loading $svc"
  launchctl load "$svc"
done

for svc in /Library/LaunchAgents/* /Library/LaunchDaemons/*; do
  echo "* Loading $svc"
  sudo launchctl load "$svc"
done
